# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('donor_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown / Typing Required')], default='UNKNOWN', max_length=10)),
                ('rh_factor', models.CharField(choices=[('POSITIVE', 'Rh Positive (+)'), ('NEGATIVE', 'Rh Negative (-)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('donor_type', models.CharField(choices=[('VOLUNTARY', 'Voluntary Non-Remunerated Donor'), ('REPLACEMENT', 'Replacement / Family Donor'), ('DIRECTED', 'Directed Donor'), ('AUTOLOGOUS', 'Autologous Donor'), ('FAMILY', 'Family Donor')], default='VOLUNTARY', max_length=30)),
                ('donor_status', models.CharField(choices=[('ACTIVE', 'Active & Eligible'), ('TEMPORARILY_DEFERRED', 'Temporarily Deferred'), ('PERMANENTLY_DEFERRED', 'Permanently Deferred'), ('BLOCKED', 'Blocked / Medically Ineligible'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=30)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='National ID / Passport')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('total_donations_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible for Donation'), ('TEMPORARILY_DEFERRED', 'Temporarily Deferred'), ('PERMANENTLY_DEFERRED', 'Permanently Deferred'), ('REJECTED', 'Medically Unfit / Rejected')], db_index=True, max_length=30)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('hemoglobin_g_dl', models.DecimalField(decimal_places=1, help_text='Hemoglobin level in g/dL', max_digits=4)),
                ('systolic_bp', models.PositiveIntegerField(help_text='Systolic Blood Pressure (mmHg)')),
                ('diastolic_bp', models.PositiveIntegerField(help_text='Diastolic Blood Pressure (mmHg)')),
                ('pulse_bpm', models.PositiveIntegerField(help_text='Pulse rate (beats per minute)')),
                ('temperature_c', models.DecimalField(decimal_places=1, default=36.6, help_text='Body Temperature (?C)', max_digits=4)),
                ('deferral_type', models.CharField(choices=[('NONE', 'None / Fit for Donation'), ('LOW_HEMOGLOBIN', 'Low Hemoglobin (< 12.5 g/dL)'), ('RECENT_TATTOO_OR_PIERCING', 'Recent Tattoo or Body Piercing (< 6-12 Months)'), ('MEDICATION', 'Contraindicated Medication (Antibiotics/Anticoagulants)'), ('TRAVEL_HISTORY', 'Endemic Malaria / Travel Deferral'), ('RECENT_ILLNESS', 'Recent Infection / Fever / Cold (< 14 Days)'), ('HIGH_RISK_BEHAVIOR', 'High Risk Behavior / Exposure'), ('UNDERWEIGHT', 'Underweight (< 45/50 kg)'), ('HYPERTENSION_OR_HYPOTENSION', 'Blood Pressure out of Safe Range'), ('PREGNANCY_OR_LACTATION', 'Pregnancy or Lactation (< 12 Months)'), ('RECENT_SURGERY', 'Major Surgery within 6 Months'), ('OTHER', 'Other Clinical Reason')], default='NONE', max_length=40)),
                ('deferral_reason', models.TextField(blank=True)),
                ('deferral_start_date', models.DateField(blank=True, null=True)),
                ('deferral_end_date', models.DateField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_conducted', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_assessments', to='donors.donor')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['donor_id'], name='donors_dono_donor_i_d643f9_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group'], name='donors_dono_blood_g_e2a174_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['donor_status'], name='donors_dono_donor_s_0124e6_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['phone'], name='donors_dono_phone_2b49f7_idx'),
        ),
    ]
