upstream lifeflow_app {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name lifeflow.org www.lifeflow.org;

    client_max_body_size 20M;

    location /static/ {
        alias /var/www/lifeflow/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /var/www/lifeflow/media/;
        expires 30d;
    }

    location / {
        proxy_pass http://lifeflow_app;
        proxy_set_header X-Forwarded-For ;
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
        proxy_redirect off;
    }
}
