# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bag_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown / Typing Required')], max_length=10)),
                ('rh_factor', models.CharField(choices=[('POSITIVE', 'Rh Positive (+)'), ('NEGATIVE', 'Rh Negative (-)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('bag_type', models.CharField(choices=[('SINGLE_350ML', 'Single Bag (350 mL - CPDA-1)'), ('SINGLE_450ML', 'Single Bag (450 mL - CPDA-1)'), ('DOUBLE_350ML', 'Double Bag (350 mL - SAGM)'), ('DOUBLE_450ML', 'Double Bag (450 mL - SAGM)'), ('TRIPLE_450ML', 'Triple Bag (450 mL - SAGM / Platelet)'), ('QUADRUPLE_450ML', 'Quadruple Bag (450 mL - Top and Bottom SAGM)'), ('APHERESIS_KIT', 'Apheresis Kit Set')], default='TRIPLE_450ML', max_length=30)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('status', models.CharField(choices=[('QUARANTINED', 'Quarantined (Pending Testing)'), ('TESTING_PENDING', 'Testing in Progress'), ('TESTED_SAFE', 'Tested Safe / Released for Use'), ('REACTIVE_UNSAFE', 'Reactive / Unsafe for Transfusion'), ('PROCESSED_TO_COMPONENTS', 'Processed to Components'), ('ISSUED', 'Issued to Patient/Hospital'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], db_index=True, default='QUARANTINED', max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('storage_location', models.CharField(default='Quarantine Shelf #1', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bag', to='donations.donation')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sample_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Testing'), ('IN_TESTING', 'Testing in Progress'), ('COMPLETED', 'Testing Completed (Pending Verification)'), ('VERIFIED', 'Verified & Approved by Medical Officer'), ('REJECTED', 'Rejected / Reactive Unit')], db_index=True, default='PENDING', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('blood_bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='laboratory.bloodbag')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('test_category', models.CharField(choices=[('ABO_RH_CONFIRMATION', 'ABO & Rh Grouping Confirmation'), ('HIV_1_2_ANTIBODY', 'HIV-1 & HIV-2 Antibody / Antigen (4th Gen)'), ('HBSAG_HEPATITIS_B', 'Hepatitis B Surface Antigen (HBsAg)'), ('HCV_ANTIBODY_HEPATITIS_C', 'Hepatitis C Virus Antibody (Anti-HCV)'), ('SYPHILIS_VDRL_TPHA', 'Syphilis Screening (VDRL / TPHA / Treponemal)'), ('MALARIA_ANTIGEN', 'Malaria Parasite / Antigen (Rapid / Smear)'), ('ANTIBODY_SCREENING', 'Irregular Red Cell Antibody Screening'), ('NAT_PCR', 'Nucleic Acid Testing (NAT-PCR) for HIV/HBV/HCV'), ('OTHER', 'Other Confirmatory Test')], max_length=40)),
                ('test_name', models.CharField(max_length=150)),
                ('result', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('NON_REACTIVE', 'Non-Reactive (Negative / Safe)'), ('REACTIVE', 'Reactive (Positive / Unsafe)'), ('INVALID', 'Invalid Assay / Retest Required'), ('INCONCLUSIVE', 'Inconclusive / Gray Zone'), ('CONFIRMED_REACTIVE', 'Confirmed Reactive (Western Blot/Confirmatory)')], db_index=True, default='PENDING', max_length=30)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kit_lot_number', models.CharField(default='LOT-2026-DEFAULT', max_length=100)),
                ('kit_expiry', models.DateField(blank=True, null=True)),
                ('quantitative_value', models.CharField(blank=True, help_text='e.g. S/CO ratio or OD value', max_length=100)),
                ('interpretation_notes', models.TextField(blank=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='laboratory.labsample')),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['test_date'],
            },
        ),
        migrations.AddIndex(
            model_name='bloodbag',
            index=models.Index(fields=['bag_id'], name='laboratory__bag_id_afe849_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbag',
            index=models.Index(fields=['blood_group', 'status'], name='laboratory__blood_g_6cbb62_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbag',
            index=models.Index(fields=['expiry_date'], name='laboratory__expiry__62d46f_idx'),
        ),
    ]
