# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('request_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('requesting_doctor', models.CharField(max_length=150)),
                ('urgency', models.CharField(choices=[('NORMAL', 'Routine / Elective (Within 24 Hours)'), ('URGENT', 'Urgent (Within 2-4 Hours)'), ('EMERGENCY', 'Immediate Life Threat / Emergency (STAT)')], db_index=True, default='NORMAL', max_length=20)),
                ('required_date_time', models.DateTimeField()),
                ('clinical_diagnosis', models.TextField()),
                ('transfusion_indication', models.TextField(blank=True)),
                ('special_requirements', models.CharField(blank=True, help_text='e.g. Leukoreduced, Irradiated, CMV Negative', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Request'), ('SUBMITTED', 'Submitted to Blood Bank'), ('UNDER_REVIEW', 'Under Medical Officer Review'), ('APPROVED', 'Approved by Medical Officer'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('RESERVED', 'Inventory Units Reserved'), ('READY_FOR_ISSUE', 'Crossmatched & Ready for Issue'), ('ISSUED', 'Issued to Hospital/Patient'), ('COMPLETED', 'Completed & Transfused'), ('REJECTED', 'Rejected by Blood Bank'), ('CANCELLED', 'Cancelled by Requestor')], db_index=True, default='SUBMITTED', max_length=30)),
                ('review_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.bloodbank')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='patients.patient')),
                ('requested_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('issue_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('recipient_name', models.CharField(help_text='Name of hospital personnel receiving the unit', max_length=150)),
                ('recipient_id_proof', models.CharField(blank=True, help_text='Staff ID or badge number', max_length=100)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crossmatch_compatible', models.BooleanField(default=True)),
                ('crossmatch_details', models.CharField(default='Crossmatch Compatible (Major & Minor Tube Technique)', max_length=200)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued to Courier/Hospital'), ('ACKNOWLEDGED', 'Received & Acknowledged at Ward'), ('CANCELLED', 'Issue Cancelled Prior to Dispatch'), ('RETURNED', 'Returned to Blood Centre')], default='ISSUED', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_authorized', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_records', to='inventory.inventoryitem')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_issued', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfused_units', to='patients.patient')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='requests_app.bloodrequest')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood (WB)'), ('PRBC', 'Packed Red Blood Cells (PRBC / RBC)'), ('PLATELET', 'Random / Single Donor Platelet (RDP/SDP)'), ('FFP', 'Fresh Frozen Plasma (FFP)'), ('CRYOPRECIPITATE', 'Cryoprecipitate Anti-Hemophilic Factor'), ('CRYOSUPERNATANT', 'Cryo-Poor Plasma (Cryosupernatant)'), ('PLASMA_FRACTION', 'Plasma for Fractionation')], default='PRBC', max_length=40)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown / Typing Required')], max_length=10)),
                ('rh_factor', models.CharField(choices=[('POSITIVE', 'Rh Positive (+)'), ('NEGATIVE', 'Rh Negative (-)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('units_requested', models.PositiveIntegerField(default=1)),
                ('units_reserved', models.PositiveIntegerField(default=0)),
                ('units_issued', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Fulfillment'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests_app.bloodrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('return_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('returned_by_name', models.CharField(max_length=150)),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cold_chain_maintained', models.BooleanField(default=True)),
                ('visual_inspection_passed', models.BooleanField(default=True)),
                ('bag_seal_intact', models.BooleanField(default=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('disposition', models.CharField(choices=[('RE_ENTRY_APPROVED', 'Approved for Inventory Re-Entry (Cold Chain Intact)'), ('QUARANTINE_FOR_INVESTIGATION', 'Quarantine for Serological / Hemolysis Investigation'), ('DISCARD_ORDERED', 'Discard Ordered (Cold Chain Violated / Seal Damaged)')], default='QUARANTINE_FOR_INVESTIGATION', max_length=40)),
                ('disposition_notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_assessments', to=settings.AUTH_USER_MODEL)),
                ('blood_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='requests_app.bloodissue')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('discard_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discard_reason', models.CharField(choices=[('EXPIRED', 'Shelf Life Expired'), ('REACTIVE_TTI', 'Transfusion-Transmissible Infection Reactive (HIV/HBV/HCV/Syphilis/Malaria)'), ('TEMPERATURE_EXCURSION', 'Cold Chain Failure / Temperature Excursion'), ('DAMAGED_BAG', 'Container Integrity Compromised / Leaking'), ('QUALITY_FAILURE', 'Clots / Hemolysis / Turbidity / Visual Quality Defect'), ('UNSUITABLE_RETURN', 'Returned Blood Unfit for Re-Issue'), ('HEMOLYZED_OR_LIPEMIC', 'Severely Hemolyzed, Icteric, or Lipemic Sample/Unit'), ('OTHER', 'Other Regulatory or Quality Failure')], max_length=40)),
                ('reason_details', models.TextField()),
                ('discard_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('biohazard_disposal_method', models.CharField(choices=[('AUTOCLAVING_INCINERATION', 'Autoclaving Followed by High-Temperature Incineration'), ('CHEMICAL_TREATMENT', 'Chemical Disinfection (1% Sodium Hypochlorite)'), ('BIOHAZARD_WASTE_VENDOR', 'Authorized Biohazard Waste Management Contractor')], default='AUTOCLAVING_INCINERATION', max_length=40)),
                ('disposal_manifest_number', models.CharField(blank=True, max_length=100)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discards_authorized', to=settings.AUTH_USER_MODEL)),
                ('discarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discards_executed', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discard_records', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-discard_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventoryitem')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='requests_app.bloodrequestitem')),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['request_id'], name='requests_ap_request_06ff58_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status', 'urgency'], name='requests_ap_status_c0151d_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['hospital', 'created_at'], name='requests_ap_hospita_5e332b_idx'),
        ),
    ]
