# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('donors', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('BLOOD_BANK_ADMIN', 'Blood Bank Administrator'), ('MEDICAL_OFFICER', 'Medical Officer'), ('LAB_TECHNICIAN', 'Laboratory Technician'), ('BLOOD_BANK_TECH', 'Blood Bank Technician'), ('RECEPTIONIST', 'Receptionist / Front Desk'), ('HOSPITAL_USER', 'Hospital / Transfusion Officer'), ('DONOR', 'Donor'), ('PATIENT', 'Patient / Recipient')], db_index=True, default='DONOR', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.bloodbank')),
                ('donor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='donors.donor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_users', to='hospitals.hospital')),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='patients.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
