# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('camps', '0001_initial'),
        ('core', '0001_initial'),
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('donation_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('donation_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood Donation'), ('APHERESIS_PLATELET', 'Apheresis Platelet (SDP)'), ('APHERESIS_PLASMA', 'Apheresis Plasma / Plasmapheresis'), ('AUTOLOGOUS', 'Autologous Pre-Deposit')], default='WHOLE_BLOOD', max_length=30)),
                ('bag_type', models.CharField(choices=[('SINGLE_350ML', 'Single Bag (350 mL - CPDA-1)'), ('SINGLE_450ML', 'Single Bag (450 mL - CPDA-1)'), ('DOUBLE_350ML', 'Double Bag (350 mL - SAGM)'), ('DOUBLE_450ML', 'Double Bag (450 mL - SAGM)'), ('TRIPLE_450ML', 'Triple Bag (450 mL - SAGM / Platelet)'), ('QUADRUPLE_450ML', 'Quadruple Bag (450 mL - Top and Bottom SAGM)'), ('APHERESIS_KIT', 'Apheresis Kit Set')], default='TRIPLE_450ML', max_length=30)),
                ('volume_ml', models.PositiveIntegerField(default=450, help_text='Volume collected in mL')),
                ('vein_used', models.CharField(choices=[('LEFT_ARM', 'Left Antecubital Vein'), ('RIGHT_ARM', 'Right Antecubital Vein')], default='LEFT_ARM', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Arrived at Facility'), ('ELIGIBILITY_PENDING', 'Eligibility Assessment Pending'), ('ELIGIBLE', 'Eligible for Donation'), ('COLLECTION_STARTED', 'Collection In Progress'), ('COLLECTED', 'Collection Completed (Pending Lab)'), ('REJECTED', 'Rejected Medically'), ('DEFERRED', 'Deferred'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed & Processed')], db_index=True, default='ARRIVED', max_length=30)),
                ('adverse_reaction', models.BooleanField(default=False)),
                ('adverse_reaction_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_record', to='appointments.appointment')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_donations', to='donors.eligibilityassessment')),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.bloodbank')),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_donations', to='camps.bloodcamp')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_performed', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor')),
            ],
            options={
                'ordering': ['-collection_date'],
                'indexes': [models.Index(fields=['donation_id'], name='donations_d_donatio_784ae2_idx'), models.Index(fields=['collection_date', 'status'], name='donations_d_collect_b70a9c_idx')],
            },
        ),
    ]
