# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_components', '0001_initial'),
        ('core', '0001_initial'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('inventory_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('item_type', models.CharField(choices=[('WHOLE_BLOOD_BAG', 'Whole Blood Bag Unit'), ('COMPONENT', 'Blood Component Unit')], default='COMPONENT', max_length=30)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown / Typing Required')], max_length=10)),
                ('rh_factor', models.CharField(choices=[('POSITIVE', 'Rh Positive (+)'), ('NEGATIVE', 'Rh Negative (-)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('component_type', models.CharField(default='WHOLE_BLOOD', max_length=40)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('collection_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Transfusion'), ('RESERVED', 'Reserved (Locked for Request)'), ('QUARANTINED', 'Quarantined (Non-Issuable)'), ('ISSUED', 'Issued to Patient/Hospital'), ('RETURNED', 'Returned from Ward'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], db_index=True, default='AVAILABLE', max_length=30)),
                ('is_locked', models.BooleanField(default=False)),
                ('blood_bag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entry', to='laboratory.bloodbag')),
                ('component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entry', to='blood_components.bloodcomponent')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quarantine_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('PENDING_SCREENING', 'Pending Laboratory Screening & Verification'), ('REACTIVE_RESULT', 'Reactive / Infectious Disease Finding'), ('TEMPERATURE_EXCURSION', 'Cold Chain Temperature Excursion'), ('DAMAGED_BAG', 'Compromised / Damaged Container / Leakage'), ('LABELING_ISSUE', 'Defective / Missing Identification Label'), ('QUALITY_INVESTIGATION', 'Adverse Event / Quality Investigation'), ('OTHER', 'Other Regulatory / SOP Quarantine')], max_length=40)),
                ('quarantine_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_released', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='inventory.inventoryitem')),
                ('quarantined_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantines_initiated', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantines_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quarantine_date'],
            },
        ),
        migrations.CreateModel(
            name='StorageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_areas', to='core.bloodbank')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('REFRIGERATOR_2_6C', 'Blood Bank Refrigerator (+2?C to +6?C)'), ('FREEZER_MINUS_20C', 'Standard Plasma Freezer (-20?C to -30?C)'), ('FREEZER_MINUS_80C', 'Ultra-Low Temperature Freezer (-40?C to -80?C)'), ('PLATELET_AGITATOR_20_24C', 'Platelet Agitator & Incubator (+20?C to +24?C)'), ('ROOM_TEMPERATURE', 'Controlled Room Temperature (+18?C to +25?C)')], max_length=40)),
                ('target_temp_c', models.DecimalField(decimal_places=1, default=4.0, max_digits=4)),
                ('min_temp_c', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('max_temp_c', models.DecimalField(decimal_places=1, default=6.0, max_digits=4)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.storagearea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoragePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rack_identifier', models.CharField(default='Rack 1', max_length=50)),
                ('shelf_identifier', models.CharField(default='Shelf 1', max_length=50)),
                ('position_identifier', models.CharField(default='Pos 1', max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='inventory.storagedevice')),
            ],
            options={
                'ordering': ['device', 'rack_identifier', 'shelf_identifier', 'position_identifier'],
                'unique_together': {('device', 'rack_identifier', 'shelf_identifier', 'position_identifier')},
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_items', to='inventory.storageposition'),
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature_celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('threshold_status', models.CharField(choices=[('NORMAL', 'Within Acceptable Range (Normal)'), ('HIGH_EXCURSION', 'High Temperature Excursion (> Max)'), ('LOW_EXCURSION', 'Low Temperature Excursion (< Min)'), ('CRITICAL', 'Critical Cold-Chain Failure')], default='NORMAL', max_length=30)),
                ('corrective_action_taken', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_logs_recorded', to=settings.AUTH_USER_MODEL)),
                ('storage_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='inventory.storagedevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['inventory_id'], name='inventory_i_invento_dd47b6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status', 'component_type', 'blood_group'], name='inventory_i_status_11b910_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['expiry_date', 'status'], name='inventory_i_expiry__2fab43_idx'),
        ),
    ]
