# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create Record'), ('UPDATE', 'Update Record'), ('DELETE', 'Delete/Deactivate'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('APPROVE', 'Medical/Supervisor Approval'), ('REJECT', 'Rejection/Disapproval'), ('RESERVE', 'Inventory Reservation'), ('CANCEL_RESERVATION', 'Cancel Reservation'), ('ISSUE', 'Blood Issue to Patient/Hospital'), ('RETURN', 'Blood Return & Triage'), ('QUARANTINE', 'Quarantine Unit'), ('RELEASE', 'Release from Quarantine'), ('DISCARD', 'Biohazard Discard/Wastage'), ('VERIFY', 'Laboratory Verification'), ('CHECK_IN', 'Appointment Check-In')], db_index=True, max_length=30)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('object_repr', models.CharField(max_length=255)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx')],
            },
        ),
    ]
