# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
        ('core', '0001_initial'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('appointment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('appointment_type', models.CharField(choices=[('BLOOD_BANK', 'Blood Centre / Main Facility'), ('CAMP', 'Blood Donation Camp'), ('MOBILE_UNIT', 'Mobile Blood Collection Van')], default='BLOOD_BANK', max_length=30)),
                ('scheduled_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 - 10:00 AM', '09:00 - 10:00 AM'), ('10:00 - 11:00 AM', '10:00 - 11:00 AM'), ('11:00 - 12:00 PM', '11:00 - 12:00 PM'), ('12:00 - 01:00 PM', '12:00 - 01:00 PM'), ('02:00 - 03:00 PM', '02:00 - 03:00 PM'), ('03:00 - 04:00 PM', '03:00 - 04:00 PM'), ('04:00 - 05:00 PM', '04:00 - 05:00 PM')], max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked-In'), ('COMPLETED', 'Donation Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-Show'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='SCHEDULED', max_length=30)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.bloodbank')),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='camps.bloodcamp')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='donors.donor')),
            ],
            options={
                'ordering': ['-scheduled_date', 'time_slot'],
                'indexes': [models.Index(fields=['scheduled_date', 'status'], name='appointment_schedul_59f00a_idx')],
            },
        ),
    ]
