# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('component_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood (WB)'), ('PRBC', 'Packed Red Blood Cells (PRBC / RBC)'), ('PLATELET', 'Random / Single Donor Platelet (RDP/SDP)'), ('FFP', 'Fresh Frozen Plasma (FFP)'), ('CRYOPRECIPITATE', 'Cryoprecipitate Anti-Hemophilic Factor'), ('CRYOSUPERNATANT', 'Cryo-Poor Plasma (Cryosupernatant)'), ('PLASMA_FRACTION', 'Plasma for Fractionation')], db_index=True, max_length=40)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown / Typing Required')], max_length=10)),
                ('rh_factor', models.CharField(choices=[('POSITIVE', 'Rh Positive (+)'), ('NEGATIVE', 'Rh Negative (-)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('prepared_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(db_index=True)),
                ('volume_ml', models.PositiveIntegerField(help_text='Volume in mL')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Transfusion'), ('RESERVED', 'Reserved for Patient'), ('QUARANTINED', 'Quarantined'), ('ISSUED', 'Issued to Patient/Hospital'), ('RETURNED', 'Returned from Clinical Ward'), ('EXPIRED', 'Expired / Shelf Life Exceeded'), ('DISCARDED', 'Discarded / Biohazard Waste')], db_index=True, default='AVAILABLE', max_length=30)),
                ('storage_location', models.CharField(default='Cold Storage Shelf A', max_length=100)),
                ('leukoreduced', models.BooleanField(default=False)),
                ('irradiated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('parent_bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='laboratory.bloodbag')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prepared_date'],
                'indexes': [models.Index(fields=['component_id'], name='blood_compo_compone_ea86dd_idx'), models.Index(fields=['component_type', 'blood_group', 'status'], name='blood_compo_compone_34163c_idx'), models.Index(fields=['expiry_date', 'status'], name='blood_compo_expiry__136bec_idx')],
            },
        ),
    ]
