# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('patient_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown / Grouping Required')], default='UNKNOWN', max_length=10)),
                ('hospital_mrn', models.CharField(blank=True, max_length=100, verbose_name='Hospital MRN/IPD No')),
                ('attending_physician', models.CharField(blank=True, max_length=150)),
                ('ward_or_room', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('transfusion_history', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_id'], name='patients_pa_patient_927c52_idx'), models.Index(fields=['blood_group'], name='patients_pa_blood_g_910db0_idx')],
            },
        ),
    ]
