# Generated by Django 6.0.6 on 2026-09-04 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('EMERGENCY_REQUEST', 'Emergency Blood Request (STAT)'), ('PENDING_SCREENING', 'Pending Laboratory Screening'), ('EXPIRING_INVENTORY', 'Expiring Inventory Alert'), ('EXPIRED_INVENTORY', 'Expired Inventory Alert'), ('REQUEST_STATUS_CHANGE', 'Request Status Updated'), ('DONATION_COMPLETED', 'Donation Completed'), ('QUARANTINE_EVENT', 'Quarantine Event Action'), ('TEMPERATURE_ALERT', 'Cold Chain Temperature Alert'), ('GENERAL', 'General System Notification')], db_index=True, default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
    ]
